### ISSUE TITLE
 Undefined variable `$code` in vendor/symplely/uv-ffi/preload.php on line 356

### ISSUE THREAD

**Issue by DaGhostman** [symplely/uv-ffi#1]
The library has some issues when running on non-standard linux distributions (in my case Fedora Remix on WSL2 - `Linux DESKTOP-R4ND0MA 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`).

<details>
<summary>Complete stacktrace</summary>

```plain
PHP Fatal error:  Uncaught TypeError: FFI::load(): Argument #1 ($filename) must be of type string, null given in /mnt/c/Users/user/projects/vendor/symplely/uv-ffi/preload.php:356
Stack trace:
#0 /mnt/c/Users/user/projects/vendor/symplely/uv-ffi/preload.php(356): FFI::load()
#1 /mnt/c/Users/user/projects/vendor/symplely/uv-ffi/preload.php(372): uv_ffi_loader()
#2 /mnt/c/Users/user/projects/vendor/composer/autoload_real.php(41): require('...')
#3 /mnt/c/Users/user/projects/vendor/composer/autoload_real.php(45): {closure}()
#4 /mnt/c/Users/user/projects/vendor/autoload.php(25): ComposerAutoloaderInit4f05bde70e0597471afed56fabe88ad1::getLoader()
#5 /mnt/c/Users/user/projects/examples/server.php(9): require_once('...')
#6 {main}
  thrown in /mnt/c/Users/user/projects/vendor/symplely/uv-ffi/preload.php on line 356
```
</details>

The error seems to occur with 
```php
$scope = \FFI::load($code);
//-------------------^ Here `code` is undefined
```

<details>
<summary>I've also investigated the linux branching logic about handling linux headers but my `$os` array looks like this</summary>

```php
array (
  'NAME' => 'Fedora Remix for WSL',
  'VERSION' => '36',
  'ID' => 'fedoraremixforwsl',
  'ID_LIKE' => 'fedora',
  'VERSION_ID' => '36',
  'PLATFORM_ID' => 'platform:f36',
  'PRETTY_NAME' => 'Fedora Remix for WSL',
  'ANSI_COLOR' => '0;34',
  'CPE_NAME' => 'cpe:/o:fedoraproject:fedora:36',
  'HOME_URL' => 'https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL',
  'SUPPORT_URL' => 'https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL',
  'BUG_REPORT_URL' => 'https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/issues',
  'PRIVACY_POLICY_URL' => 'https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/blob/master/PRIVACY.md',
  'FEDORA_REMIX_VERSION' => '36.0.5',
)
```
</details>

The issue is resolved when I wrap the remainder of the code with `isset($code)` check and it works flawlessly. I do have the `libuv-devel` dependency installed and everything is working smoothly without any further changes.

Let me know if I can help in some other way.

P.S: I would've opened a PR myself, but I haven't really delved in the FFI specifics and I am not 100% sure I know what I am doing 😅

**Comment by TheTechsTech** [comment]
Thanks for the report. 

I haven't directly tested Redhat like distro's, an PR will be welcome, but that's a edge case with that _Fedora Remix WSL_, it should show **RedHat** for `ID_LIKE`. 

The routine is the standard way to find actual Linux distribution. The info breakdown shown does not point to anything official.
> $scope = \FFI::load($code);
//-------------------^ Here `code` is undefined

If `$code` is undefined nothing should load or be working, no FFI instance created, strange if things are actually working. Your `libuv-devel` not used, just system's `libuv.so` binary library.

**Comment by DaGhostman** [comment]
Ah, I should've noticed... since I have a compiled version of [amphp/ext-uv](https://github.com/amphp/ext-uv) setup, but disabled, it was picking that one up, as you've guessed it.

Thanks!
